Release v4.1.3
tronprotocol/documentation-en pull request #55
Opened 2021-03-19 07:48 UTC by tron-highfive

2021-03-31 16:18 UTC, mary-doc approved these changes

2021-03-31 16:18 UTC, mary-doc approved these changes

2021-03-31 16:20 UTC, mary-doc approved these changes

2021-04-06 20:30 UTC, RonSherfey commented
Update release3

2021-04-06 21:20 UTC, muhammadhaffizz approved these changes

2021-04-07 00:40 UTC, alm378 commented
Update

El mar., 6 de abril de 2021 4:20 p. m., muhammadhaffizz <
***@***.***> escribió:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tronprotocol/documentation-en/pull/55#pullrequestreview-629418600>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASQBM2XCOF3X76TLYFWQBQTTHN3JNANCNFSM4ZOIP2YQ>
> .
>

2021-04-07 13:06 UTC, RonSherfey requested changes
Requesting changes 1

2021-04-11 12:56 UTC, RonSherfey approved these changes
approved changes

2021-04-11 13:45 UTC, RonSherfey approved these changes

2021-04-14 10:13 UTC, RonSherfey approved these changes
approved changes

2021-04-15 00:08 UTC, piotrm89 approved these changes

2021-04-15 00:08 UTC, piotrm89 commented on docs/releases/index.md
>  ```shell
```suggestion
```shell
```

2021-04-18 12:42 UTC, RonSherfey approved these changes

2021-06-23 07:06 UTC, closed without merging